from maven as maven
workdir /build
copy . .
run mvn clean package
run ls -al target
from java:8
workdir /app
copy --from=maven /build/target/ToDo-0.0.1-SNAPSHOT.jar app.jar
run ls
entrypoint ["/usr/bin/java", "-jar", "app.jar"]



