version: '3.7'
services:
  mysql:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=pass
    - MYSQL_DATABASE=todo
  api:
    image: benm96/jm:latest
    build: ./todoEclipse
    depends_on:
    - mysql
    ports:
    - target: 8181
      published: 8181
    restart: always
  front:
    image: benm96/npm:latest
    build: ./todoReact
    ports:
    - target: 3000
      published: 3000
  nginx:
    image: benm96/ng:latest
    build: ./nginx
    ports:
    - target: 80
      published: 80
    depends_on:
    - front
    - api
